### ISSUE TITLE
女神 训练代码什么时候开放?

### ISSUE THREAD

**Issue by 0xTechSavvy** [irfanICMLL/ETC-Real-time-Per-frame-Semantic-video-segmentation#1]
如题

**Comment by irfanICMLL** [comment]
We will release our training code after the paper is accepted.
To be honest, the code is really easy following our previous project: structure knowledge distillation.
You can reproduce it following our paper. If you have any questions, you can send an email to us.

**Comment by 0xTechSavvy** [comment]
ok, thank you
