### ISSUE TITLE
Got an error when run python tool/demo.py

### ISSUE THREAD

**Issue by fjremnav** [irfanICMLL/ETC-Real-time-Per-frame-Semantic-video-segmentation#10]
Any idea why I got an error below:

Traceback (most recent call last):
  File "tool/demo.py", line 278, in <module>
    main()
  File "tool/demo.py", line 160, in main
    a, b = model.load_state_dict(student_ckpt, strict=False)
TypeError: cannot unpack non-iterable NoneType object

Thanks,

**Comment by irfanICMLL** [comment]
You should make sure that you put the ckpt at the correct dirs in student_ckpt.
