### ISSUE TITLE
video temporal consistency

### ISSUE THREAD

**Issue by YaoooLiang** [irfanICMLL/ETC-Real-time-Per-frame-Semantic-video-segmentation#2]
你好，请问temporal consistency指标的测试代码没有公开吗？在哪里可以找到这部分代码 谢谢

**Comment by irfanICMLL** [comment]
I have released the code for evaluation the temporal consistency.

**Comment by kwea123** [comment]
Isn't this part wrongly inverted?
https://github.com/irfanICMLL/ETC-Real-time-Per-frame-Semantic-video-segmentation/blob/860c4b822923890ec3b2f2a711032ef29ad540e9/tool/eval_tc.py#L199-L200
