### ISSUE TITLE
how can I evaluate in my own video

### ISSUE THREAD

**Issue by Mambatttrj** [irfanICMLL/ETC-Real-time-Per-frame-Semantic-video-segmentation#3]

**Comment by irfanICMLL** [comment]
I suppose you want to evaluate the temporal consistency of your video.
Generate the video list following the provided example.
You only need to config the flownet, and download the pre-trained weight.
Generate the prediction results and save it in the style of the label map.
Modify here.
        for i, image_path in enumerate(data_list):
            if i > 28:
                print('done!')
            else:

The 29 represents the length of the video.

**Comment by Mambatttrj** [comment]
> 我想您想评估视频的时间一致性。
> 按照提供的示例生成视频列表。
> 您只需要配置流网并下载预训练的重量。
> 生成预测结果并将其保存为标签图的样式。
> 在这里修改。
> 对于我来说，enumerate（data_list）中的image_path：
> 如果i> 28：
> print（'done！'）
> else：
> 
> 29代表视频的长度。



> I suppose you want to evaluate the temporal consistency of your video.
> Generate the video list following the provided example.
> You only need to config the flownet, and download the pre-trained weight.
> Generate the prediction results and save it in the style of the label map.
> Modify here.
> for i, image_path in enumerate(data_list):
> if i > 28:
> print('done!')
> else:
> 
> The 29 represents the length of the video.

hi thanks. It's useful.
But evne closer, I want to see the visualization results(video is better). aha, how could I do this

**Comment by irfanICMLL** [comment]
https://github.com/irfanICMLL/ETC-Real-time-Per-frame-Semantic-video-segmentation/blob/master/tool/gen_video.py
This code will save each frame automatically in a grey map. You can transfer it into color encoding.
I synthesis the video using ffmpeg. You can also write the video with opencv-python.
