### ISSUE TITLE
Details about the evaluation of temporal consistency

### ISSUE THREAD

**Issue by chenbys** [irfanICMLL/ETC-Real-time-Per-frame-Semantic-video-segmentation#4]
Thanks for the excellent work.

(1) The loaded FlowNet is at "train", why not  "eval"?
https://github.com/irfanICMLL/ETC-Real-time-Per-frame-Semantic-video-segmentation/blob/master/tool/eval_tc.py#L202

(2) Why not ignore the occlusion region?
https://github.com/irfanICMLL/ETC-Real-time-Per-frame-Semantic-video-segmentation/blob/master/tool/eval_tc.py#L218

(3) I am interested in "the pre-trained optical flow model appears in both training and evaluation". In such a case, the evaluation depends on a fitting model, and the training with the truth optical flow (if available) will under-perform the training with that pre-trained optical flow. But this evaluation approach seems just what we can do. What's the opinion of the reviewers?

**Comment by irfanICMLL** [comment]
1) Sorry for the typos. This line (flownet.eval()) should be included. I generate all the flow map at first and then eval using the offline flow map every time. Therefore I comment out the part of generating flow maps, which makes this mistake.

2) I follow this paper "Learning Blind Video Temporal Consistency" to evaluate the temporal consistency, which does not consider the occlusion region. However, it does not affect the trend of the results.

3) It is an interesting question. I also looking for temporal consistency evaluation methods for a long time during this project. But no proper ones at that time. Using optical flow is a feasible way. At the same time, visualized videos and images also illustrate the improvement of temporal consistency. Therefore reviews do not give an opinion on the evaluation method.
