### ISSUE TITLE
lower mIoU score than reported

### ISSUE THREAD

**Issue by jfzhuang** [irfanICMLL/ETC-Real-time-Per-frame-Semantic-video-segmentation#6]
Thanks for your great work and code release. I have tested mIoU scores with demo.py on two released weights (e.g., eval_para_base.pth and eval_para_ETC.pth). The mIoU scores are 68.21 (base) vs. 71.66 (ETC), which is lower than the reported scores, 69.79 (base) vs. 73.06 (ETC). Please tell me if I have missed something. Thaks a lot!

**Comment by irfanICMLL** [comment]
We follow the PSPnet and the reported results are tested with Flip=True only for the PSPNet18. The improvement is consistent.
