### ISSUE TITLE
Which Nvidia GPU card do you use for training?

### ISSUE THREAD

**Issue by J-JunChen** [irfanICMLL/ETC-Real-time-Per-frame-Semantic-video-segmentation#8]
Hey, author!
I would like to ask which Nvidia GPU card do you use for training?
and How many cards do you use?

**Comment by irfanICMLL** [comment]
I use Volta 100 4*32GB. But it can work in 2*32GB V100,

**Comment by J-JunChen** [comment]
Ok! Thanks
