### ISSUE TITLE
Pretrain about the backbone ResNet

### ISSUE THREAD

**Issue by Jiangtong-Li** [irfanICMLL/ETC-Real-time-Per-frame-Semantic-video-segmentation#9]
Hi, 

In model/resnet.py, I find that the pretrained backbone ResNet are load from ./initmodel/resnet18.pth instead of the url path path provided by PyTorch in model_zoo.
Would you like to release the weight of the specific pretrained backbone ResNet-18?
Besides, I also find that for ResNet-50/101/152, you use the ResNet-v1 code to load the weight of ResNet-v2.
Is there any specific concern for this utilization?

**Comment by irfanICMLL** [comment]
We have set the 'deep_base=True' when loading the pre-trained weight.

The resnet18 is the same as the URL. We download it to the disk as sometimes we run code on the nodes which can not access to the Internet.
